RgbToYiq and YiqToRgb operations
KonduitAI/deeplearning4j pull request #142
Opened 2019-12-23 03:47 UTC by quickwritereader

Cpu implementation and Tests.

2019-12-23 04:57 UTC, raver119 requested changes
LGTM, but:

1) One minor tweak required for inplace execution allowance.
2) CUDA version to be added, I'll add it in this branch.

2019-12-23 04:57 UTC, raver119 commented on libnd4j/include/ops/declarable/generic/images/yiqToRgb.cpp
> +        CONFIGURABLE_OP_IMPL(yiq_to_rgb, 1, 1, false, 0, 0) {
This op clearly can be called "inplace" by the looks ok if, so let's allow that

2019-12-24 06:08 UTC, raver119 commented
Also, please stop reusing the same branch over and over again.

2019-12-24 06:58 UTC, saudet commented
> Also, please stop reusing the same branch over and over again.

Why is that a bad thing? We can think of it as a "devel" branch

2019-12-24 07:00 UTC, raver119 commented
If you have branch used and stored in CLion/Intellij it manages to store previous version of the branch, and introduces conflicts that do not exist in reality.

2019-12-24 07:10 UTC, quickwritereader commented
ok. got my lesson. will use issue named branch names

2019-12-24 10:31 UTC, saudet commented
> If you have branch used and stored in CLion/Intellij it manages to store previous version of the branch, and introduces conflicts that do not exist in reality.

That's probably just a matter of deleting your local branch with `git branch -D` or something. Unless you want to leave them around for some reason...

2019-12-24 12:20 UTC, merged