Shyrma depthconv
KonduitAI/deeplearning4j pull request #156
Opened 2020-01-01 17:34 UTC by shyrma

- provide code for depthconv2d op based on using mkl dnn corresponding api

2020-01-01 17:52 UTC, raver119 requested changes
Generally LGTM, but few minor changes required

2020-01-01 17:52 UTC, raver119 commented on libnd4j/include/ops/declarable/generic/nn/convo/depthwiseConv2d.cpp
>      REQUIRE_TRUE(expectedWeightsShape == ShapeUtils::shapeAsString(weightsShapeInfo), 0, "DEPTHWISECONV2D OP: wrong shape of weights array, expected is %s, but got %s instead !", expectedWeightsShape
While we're at it, maybe we'll finally get rid of this string stuff?

2020-01-01 17:52 UTC, raver119 commented on libnd4j/include/ops/declarable/generic/nn/convo/depthwiseConv2d.cpp
>      REQUIRE_TRUE(expectedWeightsShape == ShapeUtils::shapeAsString(weights), 0, "CUSTOM DEPTHWISECONV2D_BP OP: wrong shape of weights array, expected is %s, but got %s instead !", expectedWeightsShap
Same as above

2020-01-01 17:52 UTC, raver119 commented on libnd4j/include/ops/declarable/generic/nn/convo/depthwiseConv2d.cpp
>      REQUIRE_TRUE(expectedWeightsShape == ShapeUtils::shapeAsString(weightsShapeInfo), 0, "CUSTOM DEPTHWISECONV2D_BP OP: wrong shape of weights array, expected is %s, but got %s instead !", expectedWe
Same as above

2020-01-01 17:52 UTC, raver119 commented on libnd4j/tests_cpu/layers_tests/ConvolutionTests1.cpp
> +    auto expOutput = NDArrayFactory::create<float>('c', {bS, oC, oH, oW},{5.2, 5.2, 5.2, 5.2,20.6,20.6,20.6,20.6,14.4,14.4,14.4,14.4,29.8,29.8,29.8,29.8, 5.2, 5.2, 5.2, 5.2,20.6,20.6,20.6,20.6,14.4,1
since that's float - please add .f literal, or use constructor.

2020-01-01 17:52 UTC, raver119 commented on libnd4j/tests_cpu/layers_tests/ConvolutionTests1.cpp
> +    auto expOutput = NDArrayFactory::create<float>('c', {bS, oH, oW, oC}, {20., 24.,28., 32.,16., 18.,44., 48.,52., 56.,28., 30.,28., 30.,32., 34.,17., 18.});
Same as above

2020-01-01 17:52 UTC, raver119 commented on libnd4j/tests_cpu/layers_tests/ConvolutionTests1.cpp
> +    auto expGradW = NDArrayFactory::create<float>('c', {kH, kW, iC, mC},{19.08, 19.44,19.8 , 20.16,12.24, 12.48,12.72, 12.96,22.56, 23.04,23.52, 24. ,14.4 , 14.72,15.04, 15.36,14.76, 15.12,15.48, 15.
Same as above

2020-01-01 17:52 UTC, raver119 commented on libnd4j/tests_cpu/layers_tests/ConvolutionTests1.cpp
> +    auto expGradI = NDArrayFactory::create<float>('c', {bS, iH, iW, iC},{0.07 ,  0.19 , 0.348,  0.652, 0.588,  0.956, 0.387,  0.687, 1.326,  2.022, 1.878,  2.67 , 1.071,  1.515, 2.982,  3.966, 3.534,
Same as above

2020-01-01 17:52 UTC, raver119 commented on libnd4j/tests_cpu/layers_tests/ConvolutionTests1.cpp
> +    auto expGradI = NDArrayFactory::create<float>('c', {bS, iH, iW, iC},{0.005, 0.025,0.034, 0.106,0.061, 0.113,0.058, 0.162,0.292, 0.564,0.298, 0.466,0.234, 0.402,0.772, 1.172,0.602, 0.834,0.333, 0.
Same as above

2020-01-01 17:52 UTC, raver119 commented on libnd4j/tests_cpu/layers_tests/ConvolutionTests1.cpp
> +    auto expGradW = NDArrayFactory::create<float>('c', {kH, kW, iC, mC},{2.4 , 2.56,2.72, 2.88,2.4 , 2.56,2.72, 2.88,2.4 , 2.56,2.72, 2.88,2.4 , 2.56,2.72, 2.88,2.4 , 2.56,2.72, 2.88,2.4 , 2.56,2.72,
Same as above

2020-01-04 01:13 UTC, AlexDBlack commented
Here's 2 cases extracted from TF import graphs that are failing on this branch:

From MobileNet v2:
```
    @Test
    public void testDebugDepthwise(){
        Nd4j.getRandom().setSeed(12345);
        INDArray in = Nd4j.rand(DataType.FLOAT, 1, 112, 112, 32);
        INDArray w = Nd4j.rand(DataType.FLOAT, 3, 3, 32, 1);

        INDArray out = Nd4j.create(DataType.FLOAT, 1, 112, 112, 32);

        Nd4jCpu.Environment.getInstance().allowHelpers(false);

        DynamicCustomOp op = DynamicCustomOp.builder("depthwise_conv2d")
                .addInputs(in, w)
                .addOutputs(out)
                .addIntegerArguments(3,3,
                        1,1,
                        0,0,
                        1,1,
                        1,1)
                .build();
        Nd4j.exec(op);

        INDArray outMKL = out.like();
        op.setOutputArgument(0, outMKL);

        Nd4jCpu.Environment.getInstance().allowHelpers(true);
        Nd4j.exec(op);
        assertEquals(out, outMKL);
    }
```

From NasNet mobile:
```
    @Test
    public void testDebugDepthwise2(){
        Nd4j.getRandom().setSeed(12345);
        INDArray in = Nd4j.rand(DataType.FLOAT, 1, 111, 111, 32);
        INDArray w = Nd4j.rand(DataType.FLOAT, 7, 7, 32, 1);

        INDArray out = Nd4j.create(DataType.FLOAT, 1, 56, 56, 32);

        Nd4jCpu.Environment.getInstance().allowHelpers(false);

        DynamicCustomOp op = DynamicCustomOp.builder("depthwise_conv2d")
                .addInputs(in, w)
                .addOutputs(out)
                .addIntegerArguments(7,7,
                        2,2,
                        0,0,
                        1,1,
                        1,1)
                .build();

        Nd4j.exec(op);

        INDArray outMKL = out.like();
        op.setOutputArgument(0, outMKL);

        Nd4jCpu.Environment.getInstance().allowHelpers(true);
        Nd4j.exec(op);
        assertEquals(out, outMKL);
    }
```

2020-01-11 04:36 UTC, merged