ElementWiseStride==1 cases for legacy random ops
KonduitAI/deeplearning4j pull request #202
Opened 2020-01-30 13:56 UTC by quickwritereader

## What changes were proposed in this pull request?

ElementWiseStride==1 cases for legacy random ops were added.

## How was this patch tested?

unit tests

## Quick checklist

The following checklist helps ensure your PR is complete:

- [x] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [x] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [x] Relevant tests for your changes are passing.

2020-01-30 16:02 UTC, raver119 requested changes
Fixes required.

2020-01-30 16:02 UTC, raver119 commented on libnd4j/include/loops/cpu/random.cpp
> +                if(shape::elementWiseStride(zShapeInfo) ==  1){
in this case you must also check xShapeInfo, and ensure their orders do match

2020-01-30 16:02 UTC, raver119 commented on libnd4j/include/loops/cpu/random.cpp
> +                if(shape::elementWiseStride(zShapeInfo) ==  1){
in this case you must also check xShapeInfo and yShapeInfo, and ensure their orders do match

2020-01-30 22:20 UTC, quickwritereader commented
> Fixes required.

I added missing checks

2020-01-31 05:57 UTC, raver119 approved these changes

2020-01-31 05:57 UTC, merged