Shyrma concat
KonduitAI/deeplearning4j pull request #24
Opened 2019-11-02 17:10 UTC by shyrma

- provide deconv2d/3d (ff and bp) based on corresponding mkl dnn api
- add possibility to pass axis as last input array in concat op
- corrcect sumation in bias_add_bp op for NHWC case

2019-11-02 17:18 UTC, raver119 requested changes
Few minor changes required. Looks great otherwise.

2019-11-02 17:18 UTC, raver119 commented on libnd4j/include/ops/declarable/generic/nn/convo/deconv2d.cpp
> +    REQUIRE_TRUE(expectedWeightsShape == weights->getShapeAsVector(), 0, "CUSTOM DECONV2D OP: wrong shape of weights array, expected is %s, but got %s instead !", ShapeUtils::shapeAsString(expectedWe
Why are we doing creating 2 vectors here? Can't we make a method, that will compare EXISTING shapeInfo to `expectedWeightsShape`?

2019-11-02 17:18 UTC, raver119 commented on libnd4j/include/ops/declarable/generic/nn/convo/deconv2d.cpp
> +    REQUIRE_TRUE(expectedWeightsShape == ShapeUtils::shapeAsVector(weightsShapeInfo), 0, "CUSTOM DECONV2D OP: wrong shape of weights array, expected is %s, but got %s instead !", ShapeUtils::shapeAsS
Same as above

2019-11-02 17:18 UTC, raver119 commented on libnd4j/include/ops/declarable/generic/nn/convo/deconv2d.cpp
> +        //Note: we're intentionally swapping iH and oH, to calculated the padding for a"normal" conv (not deconv) forward pass
👍

2019-11-02 17:18 UTC, raver119 commented on libnd4j/include/ops/declarable/generic/nn/convo/deconv2d_tf.cpp
> +    REQUIRE_TRUE(expectedGradOShape == gradO->getShapeAsVector(), 0,  "CUSTOM DECONV2D_TF OP: wrong shape of input array, basing on array with output shape expected is %s, but got %s instead !", Shap
Same as above

2019-11-02 17:18 UTC, raver119 commented on libnd4j/include/ops/declarable/generic/nn/convo/deconv2d_tf.cpp
> +    REQUIRE_TRUE(gradIShapeShapeInfo[0] == 1,    0, "CUSTOM DECONV2D_TF OP: rank of array with output shape must be equal to %i, but got %i instead !", 1, gradIShapeShapeInfo[0]);
Please use shape::sizeAt() and shape::rank() instead. Don't use direct buffer comparison.

2019-11-03 10:31 UTC, shyrma commented
thank for reasonable comments,
corrrected !

2019-11-03 10:36 UTC, raver119 approved these changes

2019-11-03 10:37 UTC, merged