TF Updates
KonduitAI/deeplearning4j pull request #26
Opened 2019-11-04 10:56 UTC by farizrahman4u

2019-11-11 00:00 UTC, agibsonccc submitted a review, later dismissed

2019-11-11 00:00 UTC, agibsonccc commented on nd4j/nd4j-tensorflow/src/main/java/org/nd4j/tensorflow/conversion/TensorDataType.java
> + * Copyright (c) 2015-2018 Skymind, Inc.
Mind updating copyright to be 2019 Konduit on next line?

2019-11-11 00:01 UTC, agibsonccc commented
@farizrahman4u  go ahead and finish this up so we can just move on here. There shouldn't be too much to do here.

2019-11-20 23:46 UTC, agibsonccc commented
@farizrahman4u please make sure to run these tests on cpu/gpu: https://github.com/eclipse/deeplearning4j/tree/master/nd4j/nd4j-backends/nd4j-tests-tensorflow also look for new tests you need to backport from konduit-serving

2019-11-27 05:51 UTC, AlexDBlack requested changes
I've merged master to this branch and pushed it up

Testing this locally, I'm seeing:
(a) Dependency issue for GraphRunnerTest.testGraphRunnerFilePath and 2 others - `java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder`
(b) JVM crash on GraphRunnerTest.testGraphRunnerSavedModel (note: test already existed before this PR) - https://gist.github.com/AlexDBlack/c52f4584122731cc8d44f5cf06c10cec
(c) Missing test resource: GraphRunnerTest.testGraphRunnerCast - `java.lang.IllegalStateException: Unable to read graph cast_float32_float64.pb`


I'll take a look at the dependency issue. Not sure where that cast graph is from.

2019-11-27 06:56 UTC, farizrahman4u commented
@AlexDBlack adam uses generated graphs for dtype conversion - I forgot to check them in (`git add *.java`).

2019-11-27 06:56 UTC, closed without merging