Fixes Keras import issue (8373)
KonduitAI/deeplearning4j pull request #54
Opened 2019-11-17 10:40 UTC by farizrahman4u

Fixes [8373](https://github.com/eclipse/deeplearning4j/issues/8373)

2019-11-17 10:51 UTC, agibsonccc requested changes

2019-11-17 10:51 UTC, agibsonccc commented on deeplearning4j/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/graph/ComputationGraph.java
> +        for (String s: verticesMap.keySet()){
Get rid of debug statements

2019-11-17 10:53 UTC, agibsonccc commented
@maxpumperla pending the model being added to test resources anything else you want done here?

2019-11-18 07:51 UTC, maxpumperla commented
@agibsonccc just an actual test. it doesn't have to be the one from the issue, a minimal keras example showing the intended behavior suffices. we've had the "will add test resources later" (but never did) situation a bit too often for my taste. it's normal to forget such things, so let's just add a quick test now.

2019-11-19 03:26 UTC, agibsonccc commented
@maxpumperla cc @AlexDBlack  is this on our internal tools anywhere yet?  @sshepel how is this PR looing?

2019-11-19 07:52 UTC, maxpumperla approved these changes
thanks for the test

2019-11-20 02:18 UTC, AlexDBlack commented
I'll merge this. Waiting for CI would be better, but it's probably not reliable enough to get all the way to keras import tests without hitting an issue.
Any issues should be picked up in the pre-release QA we're doing now anyway.

2019-11-20 02:19 UTC, merged